### PR TITLE
BUG Correct cache pollution between versions

### LINKED ISSUE #62: API docs show wrong list of available classes for branch
Didn't know where to post this issue, here or in the Symfony docs repo. I'm guessing this is a generator bug.

As can be seen in this screenshot, in the list of available HttpExceptions for the 2.1 branch in the sidebar, a lot of Exceptions listed were introduced in a later version. The page shown when clicking on the namespace Symfony\Component\HttpKernel\Exception shows the correct list of available HttpExceptions.

Screenshot:
sf21-api-docs

I haven't checked if this is limited to this namespace for this branch or if this is more widespread and related to Sami.

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes #62 (four year old bug :) )

I appreciate critique regarding the removal of the cache warming between versions; My experience is that the error in the output outweigh the performance benefit, but I stand to be corrected if possible. :)

Possibly there is another caching warming / reuse pattern that could be replaced, but I'm not familiar enough with the design to implement one I'm afraid.

I had some issue with ArrayStore not respecting the project version, but out of respect I've opted not to try to shiv in a fix for it.

### CODE REVIEW

File: Sami/Renderer/Renderer.php [hunk 1]
```diff
@@ -227,12 +227,20 @@ protected function getProgression()
...
+     *
+     * @param Project $project
+     *
+     * @return array
+     */
     private function getTree(Project $project)
     {
-        if (!isset($this->cachedTree[$project])) {
-            $this->cachedTree[$project] = $this->tree->getTree($project);
+        $key = $project->getVersion()->getName();
```
Comment (fabpot) [inline Sami/Renderer/Renderer.php]: The key should probably contain the project as well, no?

Comment (aik099) [reply Sami/Renderer/Renderer.php]: That depends on average location the cache folder is placed. In default configuration cache folder for each of projects is different, so this shouldn't be an issue.

Comment (tractorcow) [reply Sami/Renderer/Renderer.php]: If we are re-using a single renderer across multiple projects, then there is a risk that project a / version 1 could conflict with version b / version 1.

Would it be sufficient for me to use `$project->getBuildDir()` as the cache instead? This will include the `%version%` substitution, thus making it distinct between versions.

Comment (tractorcow) [reply Sami/Renderer/Renderer.php]: Please see my latest commit which addresses this. :)

**Comment by fabpot** [comment]
Thank you @tractorcow.

**Comment by tractorcow** [comment]
My pleasure thanks for responding quickly.
