### PR TITLE
Adding a fix to parse the contents of a file rather than trying to parse a filename

### LINKED ISSUE #160: Phar is broken
I believe that this change has broken Sami: https://github.com/symfony/Yaml/commit/b50000adac00cfc18fcc86b576211a3a01caa550

This change was a breaking change in the Yaml component that disabled the ability to parse from a filename, but rather expects the contents of the Yaml file. Sami is relying on the form that allowed paths to files here: https://github.com/FriendsOfPHP/Sami/blob/master/Sami/Renderer/ThemeSet.php#L40

When running Same right now with a custom theme, you get this error:

```
 [InvalidArgumentException]                                                                                          
  Theme manifest in "/Users/dowling/projects/sdk3/build/artifacts/docs/theme/manifest.yml" must have a "name" entry.
```

This is because the method is being provided an SplFile object that when cast to a string provides the path to the file on disk. Yaml::parse then tries to parse the filename and fails.

Note: this is encountered when using the phar or when using a freshly built phar

### PR DESCRIPTION
**Pull request by mtdowling**
This PR closes #160 to ensure that Sami parses the contents of a yaml file rather than trying to parse the filename of a yaml file.

### CODE REVIEW

File: Sami/Renderer/ThemeSet.php [hunk 1]
```diff
@@ -37,7 +37,8 @@ protected function discover(array $dirs)
         $this->themes = array();
         $parents = array();
         foreach (Finder::create()->name('manifest.yml')->in($dirs) as $manifest) {
-            $config = Yaml::parse($manifest);
+            $text = file_get_contents($manifest);
```
Comment (aik099) [inline Sami/Renderer/ThemeSet.php]: You can safely combine both lines (this one and below).

Comment (mtdowling) [inline Sami/Renderer/ThemeSet.php]: Yes, but I'm not sure why that matters.

**Comment by fabpot** [comment]
Thank you @mtdowling.
